version: '2.0'

services:
  postgres-mgmt:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - '2181:2181'
  broker:
    image: confluentinc/cp-kafka:3.2.0
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
  schema-registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - '9010:9010'
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xms80m -Xmx150m"
      SCHEMA_REGISTRY_DEBUG: 'true'
      SCHEMA_REGISTRY_HOST_NAME: 'localhost'
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-registry:9010'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'