spring:
  application.name: audit-log-service
  kafka:
    bootstrap-servers: broker:9092
    schema-registry: http://schema-registry:9010
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create

microservices:
  kafka:
    topic:
      audit.log: audit.log

server:
  port: 8111