spring:
  application:
    name: dummy-processor-engine
  kafka:
    bootstrap-servers: broker:9092
    schema-registry: http://schema-registry:9010

microservices:
  kafka:
    topic:
      country.covid19.statistics.changed: country.covid19.statistics.changed

server:
  port: 8888